// fibonacci

// each number in the sequence is generated by adding the previous two numbers

// Fn = Fn-1 + Fn-2

// what do I need to do?

// create an array with a length equal to the given value
// the array will be created by adding the two existing preceeding numbers together then pushes the sum of those two numbers to the array
// the function traverses across the array as it builds incrementing each index position of the array by 1
// the function should return the value in the index position of the provided length - 1

const fibonacci = function (index) {
  if (index <= 0) {
    return "OOPS";
  }
  const fib = [1, 1];
  for (let i = 0, j = 1; i <= +index - 1, j <= +index; i++, j++) {
    let sum = fib[i] + fib[j];
    fib.push(sum);
  }
  return fib[index - 1];
};

// Do not edit below this line
module.exports = fibonacci;
